<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Denizen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(#\s\+\-.+|#\s\|.+)</string>
			<key>name</key>
			<string>comment.header</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.+</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[^\s?].+?:</string>
			<key>name</key>
			<string>script.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\t)</string>
			<key>name</key>
			<string>tabulator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\on </string>
			<key>end</key>
			<string>\:</string>
			<key>name</key>
			<string>events</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\  \w+</string>
			<key>end</key>
			<string>\:</string>
			<key>name</key>
			<string>Injections</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\:-&gt;:|\:&lt;-:|\+|\+\+|\*|\/|\!|\!|\=)</string>
			<key>name</key>
			<string>math</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\- (\^|)queue clear|\- (\^|)determine cancelled|\- (\^|)determine passively cancelled|\- (\^|)wait|targets:|\- (\^|)take)</string>
			<key>name</key>
			<string>destructive.command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\- (\^|)define \w+|\%.+?\%)</string>
			<key>name</key>
			<string>define.command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\- (\^|)inject \w+|\- (\^|)run \w+|inject locally \w+)</string>
			<key>name</key>
			<string>run.command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\- (\^|)determine|\- (\^|)define|\- (\^|)yaml id:|\- (\^|)execute|\- (\^|)give|\- (\^|)teleport|\- (\^|)flag|\- (\^|)finish|\- (^|)fail|\- (\^|)log|\- (\^|)new|\- (\^|)run|\- (\^|)zap|\- (\^|)queue|\- (\^|)wait|\- (\^|)narrate|\- (\^|)adjust|\- (\^|)inventory)</string>
			<key>name</key>
			<string>core.command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\- (\^|)yaml create id:|\- (\^|)yaml|\id:)</string>
			<key>name</key>
			<string>yaml.create</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\} else {|\} else if )</string>
			<key>name</key>
			<string>else.statement</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\- (\^|)if|\- (\^|)repeat|\- (\^|)random|\=\=|\!\=|\&\&|\|\||\&gt;\s|\&lt;\s|\{|\}|\- (\^|)foreach)</string>
			<key>name</key>
			<string>if.statement</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.single.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>tag_context</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\%.+?\%</string>
					<key>name</key>
					<string>define.command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;&co&gt;|\&lt;&dq&gt;|\&lt;&sq&gt;|\&lt;&s&gt;)</string>
					<key>name</key>
					<string>math</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\load:)</string>
					<key>name</key>
					<string>yaml.create</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;black&gt;|\&lt;&0&gt;)</string>
					<key>name</key>
					<string>black.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;dark_blue&gt;|\&lt;&1&gt;)</string>
					<key>name</key>
					<string>dark_blue.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;dark_green&gt;|\&lt;&2&gt;)</string>
					<key>name</key>
					<string>dark_green.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;dark_aqua&gt;|\&lt;&3&gt;)</string>
					<key>name</key>
					<string>dark_aqua.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;dark_red&gt;|\&lt;&4&gt;)</string>
					<key>name</key>
					<string>dark_red.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;dark_purple&gt;|\&lt;&5&gt;)</string>
					<key>name</key>
					<string>dark_purple.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;gold&gt;|\&lt;&6&gt;)</string>
					<key>name</key>
					<string>gold.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;gray&gt;|\&lt;&7&gt;)</string>
					<key>name</key>
					<string>gray.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;dark_gray&gt;|\&lt;&8&gt;)</string>
					<key>name</key>
					<string>dark_gray.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;blue&gt;|\&lt;&9&gt;)</string>
					<key>name</key>
					<string>blue.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;green&gt;|\&lt;&a&gt;)</string>
					<key>name</key>
					<string>green.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;aqua&gt;|\&lt;&b&gt;)</string>
					<key>name</key>
					<string>aqua.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;red&gt;|\&lt;&c&gt;)</string>
					<key>name</key>
					<string>red.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;light_purple&gt;|\&lt;&d&gt;)</string>
					<key>name</key>
					<string>light_purple.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;yellow&gt;|\&lt;&e&gt;)</string>
					<key>name</key>
					<string>yellow.color</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&lt;white&gt;|\&lt;&f&gt;)</string>
					<key>name</key>
					<string>white.color</string>
		</dict>
				<dict>
					<key>begin</key>
					<string>\&lt;</string>
					<key>end</key>
					<string>\&gt;</string>
					<key>name</key>
					<string>tag</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\%.+?\%</string>
							<key>name</key>
							<string>core.command</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\&lt;</string>
							<key>end</key>
							<string>\&gt;|"</string>
							<key>name</key>
							<string>tag2</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>tag</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>end</key>
							<string>\]</string>
							<key>name</key>
							<string>tag_context</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>tag_context</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\%.+?\%</string>
					<key>name</key>
					<string>core.command</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\&lt;</string>
					<key>end</key>
					<string>\&gt;</string>
					<key>name</key>
					<string>tag</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\%.+?\%</string>
							<key>name</key>
							<string>core.command</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\&lt;</string>
							<key>end</key>
							<string>\&gt;</string>
							<key>name</key>
							<string>tag2</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
								<dict>
									<key>include</key>
									<string>tag</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>end</key>
							<string>\]</string>
							<key>name</key>
							<string>tag_context</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;[a-zA-Z]+</string>
			<key>end</key>
			<string>\&gt;</string>
			<key>name</key>
			<string>tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%.+?\%</string>
					<key>name</key>
					<string>core.command</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\&lt;</string>
					<key>end</key>
					<string>\&gt;|"</string>
					<key>name</key>
					<string>tag2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>tag</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>tag_context</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>











	</array>
	<key>scopeName</key>
	<string>dscript.yaml</string>
	<key>uuid</key>
	<string>2A5C1E9D-96B4-4761-9B37-D989B5F96183</string>
</dict>
</plist>
